name: spub
description: A sample command-line application.
version: 0.0.1
repository: https://github.com/jayjah/spub

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  dcli: ^2.1.0
  args: ^2.3.1
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
  dart_code_metrics:

